title: Emergenics
description: Documentation and resources for Emergenics.
baseurl: "" # Leave blank for root deployment
url: "https://cognetsys.github.io/Emergenics" # Update with your production URL
theme: minima

collections:
  books:
    output: true
    permalink: /books/:categories/:title/

defaults:
  - scope:
      path: "_posts/books"
    values:
      layout: post
      categories: books
